#!/usr/bin/env python3
"""Shell tab completion for the `trirouter` command, generated from manual.py (commands, subcommands, flags and
flag values), like `gh completion -s bash`.

Internal module, no command of its own: `trirouter setup` installs the scripts (install()), `--no-completion`
skips it, `trirouter uninstall` removes them (remove()).

Installing writes the script to ~/.trirouter/completion/trirouter.<ext> and one marked block that loads it
into the shell's profile: ~/.bashrc (macOS: ~/.bash_profile), ~/.zshrc (or $ZDOTDIR/.zshrc), the PowerShell
$PROFILE of every installed edition (Windows PowerShell and pwsh, on any OS). fish autoloads
$XDG_CONFIG_HOME/fish/completions/trirouter.fish (default ~/.config), so no profile is edited. Idempotent: an up-to-date block is left alone, a changed one is replaced in place;
a profile that is changed keeps its original once as `<file>.bak`; the file's line endings are kept.
"""
import os
import re
from pathlib import Path

from . import manual, platforms as P

SHELLS = ("bash", "zsh", "fish", "powershell")
EXT = {"bash": "bash", "zsh": "zsh", "fish": "fish", "powershell": "ps1"}
BEGIN, END = "# >>> trirouter completion >>>", "# <<< trirouter completion <<<"
BLOCK_RE = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END) + r"[ \t]*(?:\r?\n)?", re.S)
NAMES = ("trirouter",)


# ---- the data, from manual.py -------------------------------------------------------------------------------

def commands():
    return list(manual.ORDER)


def keys():
    """Every command key with its own flags: "setup", "quarantine", "quarantine purge", ..."""
    return list(manual.COMMANDS)


def flags_of(key):
    """Long flags of a command key; a flag that needs a value ends in '=' (`--auto=`)."""
    out = []
    for f in manual.all_flags(manual.COMMANDS[key]):
        out.append(f.long + ("=" if f.value and not f.optional else ""))
    return out


def value_flags(key):
    return [f for f in manual.all_flags(manual.COMMANDS[key]) if f.value]


def values_of(f):
    """The values offered for a flag: the choices its hint names (`on or off`), else every choice."""
    if not f.choices:
        return []
    named = [w for w in re.findall(r"[\w-]+", f.choices_hint) if w in f.choices]
    return list(dict.fromkeys(named or f.choices))


def top_flags():
    """The flags of the bare program (`trirouter --version`), space separated."""
    return " ".join(x for long, short, _ in manual.TOP_FLAGS for x in (long, short))


def short_doc(text, limit=70):
    text = " ".join(text.split())
    first = re.split(r"(?<=[.:;])\s", text)[0].rstrip(".:;")
    return first if len(first) <= limit else first[:limit - 3].rstrip() + "..."


# ---- bash ---------------------------------------------------------------------------------------------------

def _sh_case(pairs, indent):
    return "\n".join(f'{indent}"{k}") {v};;' for k, v in pairs)


def bash_script():
    subs = manual.SUBCOMMANDS
    key_case = "\n".join(f'        {cmd}) case "$sub" in {"|".join(s)}) key="$cmd $sub";; esac;;' for cmd, s in subs.items())
    value_pairs, valued = [], []
    for k in keys():
        for f in value_flags(k):
            if f.optional:
                continue
            valued.append(f'"{k}|{f.long}"')
            value_pairs.append((f"{k}|{f.long}", f'vals="{" ".join(values_of(f))}"'))
    flag_pairs = [(k, f'opts="{" ".join(flags_of(k))}"') for k in keys()]
    sub_pairs = [(c, f'COMPREPLY=( $(compgen -W "{" ".join(s)}" -- "$cur") )') for c, s in subs.items()]
    return f"""# bash completion for trirouter -- generated by `trirouter setup` from trirouter/manual.py
_trirouter_completion() {{
    local cur="${{COMP_WORDS[COMP_CWORD]}}" prev="" flag="" prefix="" key cmd sub w i skip=0 vals="" opts=""
    local -a pos=()
    (( COMP_CWORD > 0 )) && prev="${{COMP_WORDS[COMP_CWORD-1]}}"
    # bash splits --flag=value at '=' (COMP_WORDBREAKS); zsh's bashcompinit and some setups do not
    if [[ "$cur" == "=" ]]; then
        flag="$prev"; cur=""
    elif [[ "$prev" == "=" && $COMP_CWORD -gt 1 ]]; then
        flag="${{COMP_WORDS[COMP_CWORD-2]}}"
    elif [[ "$cur" == --*=* ]]; then
        flag="${{cur%%=*}}"; prefix="$flag="; cur="${{cur#*=}}"
    fi
    for (( i=1; i<COMP_CWORD; i++ )); do
        w="${{COMP_WORDS[i]}}"
        if (( skip )); then skip=0; continue; fi
        if [[ "$w" == "=" ]]; then skip=1; continue; fi
        [[ "$w" == -* ]] && continue
        pos+=("$w")
    done
    cmd="${{pos[0]}}"; sub="${{pos[1]}}"; key="$cmd"
    case "$cmd" in
{key_case}
    esac
    if [[ -z "$flag" && "$prev" == --* && "$cur" != -* ]]; then
        case "$key|$prev" in
            {"|".join(valued) or '"-"'}) flag="$prev";;
        esac
    fi
    if [[ -n "$flag" ]]; then
        case "$key|$flag" in
{_sh_case(value_pairs, "            ")}
        esac
        COMPREPLY=( $(compgen -P "$prefix" -W "$vals" -- "$cur") )
        return 0
    fi
    if [[ -z "$cmd" ]]; then
        if [[ "$cur" == -* ]]; then
            COMPREPLY=( $(compgen -W "{top_flags()}" -- "$cur") )
        else
            COMPREPLY=( $(compgen -W "{" ".join(commands())}" -- "$cur") )
        fi
        return 0
    fi
    if [[ "$cur" == -* ]]; then
        case "$key" in
{_sh_case(flag_pairs, "            ")}
        esac
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        if [[ ${{#COMPREPLY[@]}} -eq 1 && "${{COMPREPLY[0]}}" == *= ]]; then compopt -o nospace 2>/dev/null; fi
        return 0
    fi
    if [[ "$cmd" == help ]]; then
        if (( ${{#pos[@]}} == 1 )); then
            COMPREPLY=( $(compgen -W "{" ".join(commands())}" -- "$cur") )
        elif (( ${{#pos[@]}} == 2 )); then
            case "$sub" in
{_sh_case(sub_pairs, "                ")}
            esac
        fi
        return 0
    fi
    if (( ${{#pos[@]}} == 1 )); then
        case "$cmd" in
{_sh_case(sub_pairs, "            ")}
        esac
    fi
    return 0
}}
complete -o default -F _trirouter_completion {" ".join(NAMES)}
"""


# ---- zsh ----------------------------------------------------------------------------------------------------

def _zq(text):
    """A single-quoted zsh word."""
    return "'" + text.replace("'", "'\\''") + "'"


def zsh_script():
    subs = manual.SUBCOMMANDS
    described = " ".join(_zq(c + ":" + short_doc(manual.COMMANDS[c].summary).replace(":", "\\:")) for c in commands())
    key_case = "\n".join(f'        {cmd}) case "$sub" in {"|".join(s)}) key="$cmd $sub";; esac;;' for cmd, s in subs.items())
    value_pairs = []
    for k in keys():
        for f in value_flags(k):
            if not f.optional:
                value_pairs.append((f"{k}|{f.long}", f"vals=({' '.join(values_of(f))})"))
    bool_pairs = [(k, f"opts=({' '.join(x for x in flags_of(k) if not x.endswith('='))}); "
                      f"valopts=({' '.join(x for x in flags_of(k) if x.endswith('='))})") for k in keys()]
    sub_pairs = [(c, f"compadd -- {' '.join(s)}") for c, s in subs.items()]
    return f"""#compdef trirouter
# zsh completion for trirouter -- generated by `trirouter setup` from trirouter/manual.py
_trirouter() {{
    local cur="${{words[CURRENT]}}" prev="${{words[CURRENT-1]}}" key cmd sub w i
    local -a pos vals opts valopts cmds
    for (( i=2; i<CURRENT; i++ )); do
        w="${{words[i]}}"
        [[ "$w" == -* ]] && continue
        pos+=("$w")
    done
    cmd="${{pos[1]}}"; sub="${{pos[2]}}"; key="$cmd"
    case "$cmd" in
{key_case}
    esac
    if [[ "$cur" == --*=* ]]; then
        case "$key|${{cur%%=*}}" in
{_sh_case(value_pairs, "            ")}
        esac
        compset -P '*='
        compadd -- $vals
        return
    fi
    if [[ "$prev" == --* && "$cur" != -* ]]; then
        case "$key|$prev" in
{_sh_case([(k, v + "; compadd -- $vals; return") for k, v in value_pairs], "            ")}
        esac
    fi
    if [[ -z "$cmd" ]]; then
        if [[ "$cur" == -* ]]; then
            compadd -- {top_flags()}
            return
        fi
        cmds=({described})
        _describe -t commands 'trirouter command' cmds
        return
    fi
    if [[ "$cur" == -* ]]; then
        case "$key" in
{_sh_case(bool_pairs, "            ")}
        esac
        compadd -- $opts
        compadd -S '' -- $valopts
        return
    fi
    if [[ "$cmd" == help ]]; then
        if (( ${{#pos}} == 1 )); then
            compadd -- {" ".join(commands())}
        elif (( ${{#pos}} == 2 )); then
            case "$sub" in
{_sh_case(sub_pairs, "                ")}
            esac
        fi
        return
    fi
    if (( ${{#pos}} == 1 )); then
        case "$cmd" in
{_sh_case(sub_pairs, "            ")}
        esac
    fi
}}
if (( ! $+functions[compdef] )); then
    autoload -Uz compinit && compinit -i
fi
compdef _trirouter {" ".join(NAMES)}
"""


# ---- fish ---------------------------------------------------------------------------------------------------

def _fq(text):
    return "'" + text.replace("\\", "\\\\").replace("'", "\\'") + "'"


def fish_script():
    subs = manual.SUBCOMMANDS
    out = ["# fish completion for trirouter -- generated by `trirouter setup` from trirouter/manual.py",
           "complete -c trirouter -f"]
    for c in commands():
        out.append(f"complete -c trirouter -n __fish_use_subcommand -a {c} -d {_fq(short_doc(manual.COMMANDS[c].summary))}")
    for c, s in subs.items():
        cond = f"__fish_seen_subcommand_from {c}; and not __fish_seen_subcommand_from {' '.join(s)}"
        for x in s:
            out.append(f"complete -c trirouter -n {_fq(cond)} -a {x} -d {_fq(short_doc(manual.COMMANDS[c + ' ' + x].summary))}")
    for long, short, doc in manual.TOP_FLAGS:
        out.append(f"complete -c trirouter -n __fish_use_subcommand -l {long[2:]} -s {short[1:]} -d {_fq(doc.rstrip('.'))}")
    out.append(f"complete -c trirouter -n {_fq('__fish_seen_subcommand_from help')} -a {_fq(' '.join(commands()))}")
    for k in keys():
        words = k.split()
        cond = "; and ".join(f"__fish_seen_subcommand_from {w}" for w in words)
        if len(words) == 1 and words[0] in subs:  # flags of the bare command, before a subcommand
            cond += f"; and not __fish_seen_subcommand_from {' '.join(subs[words[0]])}"
        for f in manual.all_flags(manual.COMMANDS[k]):
            parts = [f"complete -c trirouter -n {_fq(cond)} -l {f.long[2:]}"]
            if f.short:
                parts.append(f"-s {f.short[1:]}")
            if f.value and values_of(f):
                parts.append(f"-x -a {_fq(' '.join(values_of(f)))}")
            elif f.value:
                parts.append("-r")
            parts.append(f"-d {_fq(short_doc(f.doc))}")
            out.append(" ".join(parts))
    return "\n".join(out) + "\n"


# ---- PowerShell ---------------------------------------------------------------------------------------------

def _pq(text):
    return "'" + text.replace("'", "''") + "'"


def powershell_script():
    subs = manual.SUBCOMMANDS
    cmds = "; ".join(f"{_pq(c)} = {_pq(short_doc(manual.COMMANDS[c].summary))}" for c in commands())
    subl = "; ".join(f"{_pq(c)} = @({', '.join(_pq(x) for x in s)})" for c, s in subs.items())
    flags = "\n".join(f"        {_pq(k)} = @({', '.join(_pq(x) for x in flags_of(k))})" for k in keys())
    vals, docs = [], []
    for k in keys():
        for f in manual.all_flags(manual.COMMANDS[k]):
            docs.append(f"        {_pq(k + '|' + f.long)} = {_pq(short_doc(f.doc))}")
            if f.value and not f.optional:
                vals.append(f"        {_pq(k + '|' + f.long)} = @({', '.join(_pq(v) for v in values_of(f))})")
    top = "; ".join(f"{_pq(long)} = {_pq(doc.rstrip('.'))}; {_pq(short)} = {_pq(doc.rstrip('.'))}"
                    for long, short, doc in manual.TOP_FLAGS)
    names = ", ".join(_pq(n) for n in NAMES + tuple(n + ".cmd" for n in NAMES))
    return f"""# PowerShell completion for trirouter -- generated by `trirouter setup` from trirouter/manual.py
$global:__trirouterCompleter = {{
    param($wordToComplete, $commandAst, $cursorPosition)
    $commands = [ordered]@{{ {cmds} }}
    $subcommands = @{{ {subl} }}
    $top = [ordered]@{{ {top} }}
    $flags = @{{
{flags}
    }}
    $values = @{{
{chr(10).join(vals)}
    }}
    $docs = @{{
{chr(10).join(docs)}
    }}
    $word = "$wordToComplete"
    $before = @($commandAst.CommandElements | Select-Object -Skip 1 |
        Where-Object {{ $_.Extent.EndOffset -lt $cursorPosition }} | ForEach-Object {{ $_.Extent.Text }})
    $pos = @($before | Where-Object {{ $_ -notlike '-*' }})
    $prev = if ($before.Count) {{ $before[-1] }} else {{ '' }}
    $cmd = if ($pos.Count -ge 1) {{ $pos[0] }} else {{ '' }}
    $sub = if ($pos.Count -ge 2) {{ $pos[1] }} else {{ '' }}
    $key = $cmd
    if ($subcommands.Contains($cmd) -and $subcommands[$cmd] -contains $sub) {{ $key = "$cmd $sub" }}
    $emit = {{
        param($text, $kind, $tip)
        if (-not $tip) {{ $tip = $text }}
        [System.Management.Automation.CompletionResult]::new($text, $text, $kind, $tip)
    }}
    if ($word -match '^(--[\\w-]+)=(.*)$') {{
        $flag = $Matches[1]; $typed = $Matches[2]
        foreach ($v in @($values["$key|$flag"])) {{ if ($v -and $v -like "$typed*") {{ & $emit "$flag=$v" 'ParameterValue' $v }} }}
        return
    }}
    if ($prev -like '--*' -and $word -notlike '-*' -and $values.Contains("$key|$prev")) {{
        foreach ($v in @($values["$key|$prev"])) {{ if ($v -and $v -like "$word*") {{ & $emit $v 'ParameterValue' $v }} }}
        return
    }}
    if (-not $cmd) {{
        if ($word -like '-*') {{
            foreach ($t in $top.Keys) {{ if ($t -like "$word*") {{ & $emit $t 'ParameterName' $top[$t] }} }}
            return
        }}
        foreach ($c in $commands.Keys) {{ if ($c -like "$word*") {{ & $emit $c 'ParameterValue' $commands[$c] }} }}
        return
    }}
    if ($word -like '-*') {{
        foreach ($f in @($flags[$key])) {{
            if ($f -and $f -like "$word*") {{ & $emit $f 'ParameterName' $docs["$key|$($f.TrimEnd('='))"] }}
        }}
        return
    }}
    if ($cmd -eq 'help') {{
        if ($pos.Count -eq 1) {{
            foreach ($c in $commands.Keys) {{ if ($c -like "$word*") {{ & $emit $c 'ParameterValue' $commands[$c] }} }}
        }} elseif ($pos.Count -eq 2 -and $subcommands.Contains($sub)) {{
            foreach ($s in $subcommands[$sub]) {{ if ($s -like "$word*") {{ & $emit $s 'ParameterValue' $s }} }}
        }}
        return
    }}
    if ($pos.Count -eq 1 -and $subcommands.Contains($cmd)) {{
        foreach ($s in $subcommands[$cmd]) {{ if ($s -like "$word*") {{ & $emit $s 'ParameterValue' $s }} }}
    }}
}}
Register-ArgumentCompleter -Native -CommandName {names} -ScriptBlock $global:__trirouterCompleter

# PowerShell never hands a bare `-` or `--` (parameter / end-of-parameters tokens) to a native completer. This
# wrapper adds trirouter's flags only when the built-in completion found nothing for such a word on a trirouter
# command line; everything else is passed through unchanged.
if (-not $global:__trirouterTabExpansion2) {{
    $global:__trirouterTabExpansion2 = ${{function:TabExpansion2}}
    function global:TabExpansion2 {{
        [CmdletBinding(DefaultParameterSetName = 'ScriptInputSet')]
        param(
            [Parameter(ParameterSetName = 'ScriptInputSet', Mandatory = $true, Position = 0)]
            [string] $inputScript,
            [Parameter(ParameterSetName = 'ScriptInputSet', Position = 1)]
            [int] $cursorColumn = $inputScript.Length,
            [Parameter(ParameterSetName = 'AstInputSet', Mandatory = $true, Position = 0)]
            [System.Management.Automation.Language.Ast] $ast,
            [Parameter(ParameterSetName = 'AstInputSet', Mandatory = $true, Position = 1)]
            [System.Management.Automation.Language.Token[]] $tokens,
            [Parameter(ParameterSetName = 'AstInputSet', Mandatory = $true, Position = 2)]
            [System.Management.Automation.Language.IScriptPosition] $positionOfCursor,
            [Parameter(ParameterSetName = 'ScriptInputSet', Position = 2)]
            [Parameter(ParameterSetName = 'AstInputSet', Position = 3)]
            [Hashtable] $options = $null
        )
        $result = & $global:__trirouterTabExpansion2 @PSBoundParameters
        try {{
            if ($PSCmdlet.ParameterSetName -eq 'ScriptInputSet' -and $result -and $result.CompletionMatches.Count -eq 0) {{
                $text = $inputScript.Substring(0, [Math]::Min($cursorColumn, $inputScript.Length))
                if ($text -match '(?:^|\\s)(-{{1,2}})$') {{
                    $word = $Matches[1]
                    $parsed = [System.Management.Automation.Language.Parser]::ParseInput($text, [ref]$null, [ref]$null)
                    $cmdAst = $parsed.FindAll({{ param($a) $a -is [System.Management.Automation.Language.CommandAst] }}, $true) |
                        Sort-Object {{ $_.Extent.StartOffset }} | Select-Object -Last 1
                    if ($cmdAst -and @({names}) -contains $cmdAst.GetCommandName()) {{
                        $found = New-Object 'System.Collections.ObjectModel.Collection[System.Management.Automation.CompletionResult]'
                        foreach ($m in @(& $global:__trirouterCompleter $word $cmdAst $text.Length)) {{
                            if ($m) {{ $found.Add($m) }}
                        }}
                        if ($found.Count) {{
                            $result = [System.Management.Automation.CommandCompletion]::new(
                                $found, -1, $text.Length - $word.Length, $word.Length)
                        }}
                    }}
                }}
            }}
        }} catch {{ }}
        $result
    }}
}}
"""


SCRIPTS = {"bash": bash_script, "zsh": zsh_script, "fish": fish_script, "powershell": powershell_script}


def script(shell):
    return SCRIPTS[shell]()


def detect_shell(env=None):
    """The user's shell: $SHELL's name when it is bash, zsh or fish (Git Bash sets it on Windows too), else the
    platform default -- PowerShell on Windows, zsh on macOS, bash on Linux."""
    env = os.environ if env is None else env
    name = Path(env.get("SHELL") or "").name.lower().removesuffix(".exe")
    if name in ("bash", "zsh", "fish"):
        return name
    return "powershell" if P.IS_WINDOWS else "zsh" if P.IS_MAC else "bash"


def setup_shells(env=None):
    """What setup installs for: the user's shell, plus PowerShell on Windows (Windows PowerShell and pwsh) and
    wherever pwsh is installed (macOS, Linux)."""
    shells = [detect_shell(env)]
    if "powershell" not in shells and (P.IS_WINDOWS or P.find_exe("pwsh")):
        shells.append("powershell")
    return shells


# ---- install ------------------------------------------------------------------------------------------------

def script_dir():
    return P.HOME / ".trirouter" / "completion"  # the path the profile blocks name ($HOME/.trirouter/...)


def script_path(shell):
    if shell == "fish":
        base = Path(os.environ.get("XDG_CONFIG_HOME") or P.HOME / ".config")
        return base / "fish" / "completions" / "trirouter.fish"
    return script_dir() / f"trirouter.{EXT[shell]}"


def profile_block(shell):
    """The marked block for a profile; None for fish, which autoloads its completions folder."""
    if shell == "fish":
        return None
    if shell == "powershell":
        body = ("$trirouterCompletion = Join-Path $HOME '.trirouter/completion/trirouter.ps1'\n"
                "if (Test-Path $trirouterCompletion) { . $trirouterCompletion }\n"
                "Remove-Variable trirouterCompletion")
    else:
        rel = f".trirouter/completion/trirouter.{EXT[shell]}"
        body = f'[ -f "$HOME/{rel}" ] && . "$HOME/{rel}"'
    return f"{BEGIN}\n{body}\n{END}\n"


def powershell_profiles():
    """$PROFILE (current user, current host) of every installed PowerShell edition, asked from PowerShell itself
    (Documents may be redirected, e.g. to OneDrive)."""
    found = []
    for exe in ("pwsh", "powershell") if P.IS_WINDOWS else ("pwsh",):
        path = P.find_exe(exe)
        if not path:
            continue
        code, out = P.run([path, "-NoProfile", "-NonInteractive", "-Command", "$PROFILE.CurrentUserCurrentHost"], timeout=60)
        line = (out.strip().splitlines() or [""])[-1].strip()
        if code == 0 and line.lower().endswith(".ps1"):
            found.append(Path(line))
        elif not P.IS_WINDOWS:  # pwsh's documented default on macOS / Linux
            base = Path(os.environ.get("XDG_CONFIG_HOME") or P.HOME / ".config")
            found.append(base / "powershell" / "Microsoft.PowerShell_profile.ps1")
    return list(dict.fromkeys(found))


def profiles(shell):
    """The profile files a shell's block goes into. bash: ~/.bashrc, but ~/.bash_profile on macOS, whose
    terminals start login shells that do not read ~/.bashrc."""
    if shell == "bash":
        return [P.HOME / (".bash_profile" if P.IS_MAC else ".bashrc")]
    if shell == "zsh":
        return [Path(os.environ.get("ZDOTDIR") or P.HOME) / ".zshrc"]
    if shell == "powershell":
        return powershell_profiles()
    return []


def _read(path):
    """(text with \\n line ends, newline style), or (None, default) when missing; raises UnicodeDecodeError."""
    if not path.exists():
        return None, ("\r\n" if P.IS_WINDOWS and path.suffix.lower() == ".ps1" else "\n")
    raw = path.read_bytes()
    text = raw.decode("utf-8-sig") if raw.startswith(b"\xef\xbb\xbf") else raw.decode("utf-8")
    return text.replace("\r\n", "\n"), ("\r\n" if b"\r\n" in raw else "\n")


def _write(path, text, label, apply, say, newline="\n", backup=False):
    """Writes when the content differs; returns True when it changed (or would)."""
    try:
        old, style = _read(path)
    except (OSError, UnicodeDecodeError) as exc:
        say(f"[!!]  {label}: {path} is not readable as UTF-8 ({type(exc).__name__}); left alone")
        return False
    if old == text:
        say(f"[OK]  {label}: up to date ({path})")
        return False
    say(("[DO]  " if apply else "[DRY] ") + f"{label}: {'update' if old is not None else 'create'} {path}")
    if apply:
        path.parent.mkdir(parents=True, exist_ok=True)
        bak = path.with_name(path.name + ".bak")
        if backup and old is not None and not bak.exists():
            P.atomic_write(bak, path.read_bytes())
        P.atomic_write(path, text, newline=newline if old is None else style)
    return True


def with_block(text, block):
    """`text` with the marked block replaced (in place) or appended; block None removes it."""
    text = text or ""
    if BLOCK_RE.search(text):
        return BLOCK_RE.sub(lambda _m: block or "", text, count=1)
    if block is None:
        return text
    if not text:
        return block
    return text.rstrip("\n") + "\n\n" + block


def install(shells, apply=True, say=print):
    """Writes the script and the profile block for each shell; returns the number of files changed."""
    changes = 0
    for shell in shells:
        changes += _write(script_path(shell), script(shell), f"{shell} completion script", apply, say)
        block = profile_block(shell)
        targets = profiles(shell) if block else []
        if block and not targets:
            say(f"[!!]  {shell} completion: no profile found (is {shell} installed?)")
        for prof in targets:
            try:
                old, _ = _read(prof)
            except (OSError, UnicodeDecodeError):
                old = None
            changes += _write(prof, with_block(old, block), f"{shell} profile", apply, say, backup=True,
                              newline="\r\n" if shell == "powershell" and P.IS_WINDOWS else "\n")
    return changes


def installed():
    """Shells whose script is in place (setup refreshes those even when asked to skip the profile)."""
    return [s for s in SHELLS if script_path(s).is_file()]


def remove(apply=True, say=print, shells=SHELLS):
    """Removes the profile blocks and the scripts; returns the number of files changed."""
    changes = 0
    for shell in shells:
        for prof in profiles(shell) if profile_block(shell) else []:
            try:
                old, _ = _read(prof)
            except (OSError, UnicodeDecodeError):
                continue
            if old is not None and BLOCK_RE.search(old):
                changes += _write(prof, with_block(old, None), f"{shell} profile", apply, say, backup=True)
        path = script_path(shell)
        if path.is_file():
            changes += 1
            say(("[DO]  " if apply else "[DRY] ") + f"{shell} completion script: remove {path}")
            if apply:
                path.unlink()
    return changes

