#!/usr/bin/env python3
"""Installs or removes the router's hooks and MCP server for Claude Code, Codex and Antigravity.

Every entry calls a shim in ~/.trirouter/bin/, so moving the repository only requires re-running
the installer. A changed file's original is kept once as `<file>.bak`; a config file that is not
valid JSON is reported and left untouched.

    claude       UserPromptSubmit, Stop, StopFailure, SessionEnd, SubagentStart    ~/.claude/settings.json
    codex        UserPromptSubmit + Stop    ~/.codex/hooks.json (trust once via /hooks)
    antigravity  PreInvocation + Stop       ~/.gemini/config/hooks.json

It also installs the `trirouter` command: a launcher in ~/.trirouter/bin (Windows: trirouter.cmd, with
that folder added to the USER PATH; macOS / Linux: an executable plus a link in ~/.local/bin).
"""
import json
import ntpath
import os
import re
import sys
from pathlib import Path

from . import legacy, platforms as P

REPO = Path(__file__).resolve().parent.parent
BIN = P.STATE / "bin"
LEGACY_BIN = P.HOME / legacy.STATE_NAME / "bin"  # the pre-rename shim folder: re-pointed, never written
SHIM_HOOK, SHIM_MCP, SHIM_ROUTE = BIN / "run_hook.py", BIN / "mcp_server.py", BIN / "route.py"
LOCAL_BIN = P.HOME / ".local" / "bin"  # macOS / Linux: where the `trirouter` link goes
ALL = ("claude", "codex", "antigravity")
MCP_NAME = "trirouter"  # server name in the tools' configs
SHIM_TEMPLATE = '''# generated by trirouter's installer - runs {target} from the repository
import runpy, sys
sys.path.insert(0, r"{repo}")
{argv}runpy.run_module("{module}", run_name="__main__", alter_sys=True)
'''


def shim(module, command=None):
    """Shim source that runs `module` from this repository; `command` becomes its first argument."""
    argv = f'sys.argv[1:1] = ["{command}"]\n' if command else ""
    target = f"{module} {command}" if command else module
    return SHIM_TEMPLATE.format(target=target, repo=REPO, module=module, argv=argv)


class Writer:
    def __init__(self, apply):
        self.apply = apply
        self.changes = 0

    def write(self, path, content, label):
        path = Path(path)
        old = path.read_text(encoding="utf-8") if path.exists() else None
        if old == content:
            print(f"[OK]  {label}: up to date")
            return
        self.changes += 1
        print(("[DO]  " if self.apply else "[DRY] ") + f"{label}: {'update' if old is not None else 'create'} {path}")
        if self.apply:
            path.parent.mkdir(parents=True, exist_ok=True)
            bak = path.with_name(path.name + ".bak")
            if old is not None and not bak.exists():  # keep the original, pre-trirouter version
                bak.write_text(old, encoding="utf-8")
            path.write_text(content, encoding="utf-8")


def fwd(p):
    return str(p).replace("\\", "/")


class BadConfig(Exception):
    pass


def load(path):
    path = Path(path)
    if not path.exists() or not path.read_text(encoding="utf-8").strip():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8-sig"))
    except ValueError as exc:
        raise BadConfig(f"{path} is not valid JSON ({exc}) - fix it, then re-run") from exc
    if not isinstance(data, dict):
        raise BadConfig(f"{path} does not contain a JSON object - fix it, then re-run")
    return data


# A hook command is ours when it mentions one of these: the current and the pre-rename module / shim path
# ("router/run_hook.py" is an even older layout). Old entries are replaced, never duplicated.
HOOK_MARKERS = ("router/run_hook.py", "trirouter.hooks", ".trirouter/bin/run_hook.py",
                legacy.PACKAGE + ".hooks", legacy.STATE_NAME + "/bin/run_hook.py")


def is_router_cmd(cmd):
    c = (cmd or "").replace("\\", "/").lower()
    return (any(m in c for m in HOOK_MARKERS)
            or fwd(SHIM_HOOK).lower() in c or fwd(P.short_path(SHIM_HOOK)).lower() in c)


def is_legacy_cmd(cmd):
    """A hook command written before the rename: it points at the old shim folder or module."""
    c = (cmd or "").replace("\\", "/").lower()
    return legacy.PACKAGE + ".hooks" in c or legacy.STATE_NAME + "/bin/" in c


def hook_cmd(provider, event):
    return f"{P.python_cmd()} {P.shell_arg(SHIM_HOOK)} {provider} {event}"


def _strip_router(groups):
    kept = []
    for g in groups or []:
        hs = [h for h in g.get("hooks", []) if not is_router_cmd(h.get("command"))]
        if hs:
            kept.append({**g, "hooks": hs})
    return kept


HOOK_EVENTS = {
    # StopFailure / SessionEnd release the queue when a turn dies on an API error or the session ends;
    # SubagentStart records which worker the model really delegated to.
    # SessionStart purges expired quarantine entries (at most every 6 hours) and starts the daily model check;
    # it prints only a one-line note when that check changed the model list
    "claude": ("UserPromptSubmit", "Stop", "StopFailure", "SessionEnd", "SubagentStart", "SessionStart"),
    "codex": ("UserPromptSubmit", "Stop"),
}
ROUTER_EVENTS = tuple(dict.fromkeys(e for events in HOOK_EVENTS.values() for e in events))


def claude_codex_hooks(path, provider, w, uninstall=False):
    cfg = load(path)
    hooks = cfg.setdefault("hooks", {})
    wanted = () if uninstall else HOOK_EVENTS[provider]
    for event in ROUTER_EVENTS:
        if event not in hooks and event not in wanted:
            continue
        groups = _strip_router(hooks.get(event))
        matcher = provider == "codex" and event == "UserPromptSubmit"
        if event in wanted:
            entry = {"hooks": [{"type": "command", "command": hook_cmd(provider, event), "timeout": 10}]}
            groups.append({"matcher": "*", **entry} if matcher else entry)
        if groups:
            hooks[event] = groups
        else:
            hooks.pop(event, None)
    if not hooks:
        cfg.pop("hooks", None)
    w.write(path, json.dumps(cfg, indent=2, ensure_ascii=False) + "\n", f"{provider} hooks")


AGY_EVENTS = ("PreToolUse", "PostToolUse", "PreInvocation", "PostInvocation", "Stop")


def _strip_router_events(spec):
    for event in ("PreInvocation", "Stop"):
        if event in spec:
            spec[event] = [h for h in spec[event] if not is_router_cmd(h.get("command"))]
            if not spec[event]:
                del spec[event]


def antigravity_hooks(path, w, uninstall=False):
    cfg = load(path)
    for spec in cfg.values():
        if isinstance(spec, dict):
            _strip_router_events(spec)
    cfg = {name: spec for name, spec in cfg.items()
           if not isinstance(spec, dict) or any(k in spec for k in AGY_EVENTS)}
    if not uninstall:
        cfg["router"] = {e: [{"type": "command", "command": hook_cmd("antigravity", e), "timeout": 10}]
                         for e in ("PreInvocation", "Stop")}
    w.write(path, json.dumps(cfg, indent=2, ensure_ascii=False) + "\n", "antigravity hooks")


def json_mcp(path, label, w, uninstall=False):
    cfg = load(path)
    servers = cfg.setdefault("mcpServers", {})
    servers.pop(legacy.MCP_NAME, None)  # the pre-rename entry is ours: replaced, never left next to the new one
    if uninstall:
        servers.pop(MCP_NAME, None)
    else:
        # MCP clients exec "command" directly, without a shell: never shell-quoted
        servers[MCP_NAME] = {"command": fwd(P.python_exe_windowless()), "args": [fwd(SHIM_MCP)]}
    w.write(path, json.dumps(cfg, indent=2, ensure_ascii=False) + "\n", label)


def codex_mcp(path, w, uninstall=False):
    text = Path(path).read_text(encoding="utf-8") if Path(path).exists() else ""
    # the section ends at the next table or comment line (our generated agents block starts with one)
    # A pre-rename [mcp_servers.<old name>] section is ours too: the first section found is replaced in place by
    # the new one (other generated blocks may follow it), any further one is dropped.
    pat = re.compile(r"\[mcp_servers\.(?:" + re.escape(MCP_NAME) + "|" + re.escape(legacy.MCP_NAME) + r")\]\n"
                     r"(?:\n|[^\[#\n].*(?:\n|\Z))*")
    block = (f'[mcp_servers.{MCP_NAME}]\ncommand = {json.dumps(fwd(P.python_exe_windowless()))}\n'
             f'args = [{json.dumps(fwd(SHIM_MCP))}]\n\n')
    seen = []

    def replace(_match):
        seen.append(1)
        return block if len(seen) == 1 and not uninstall else ""
    new = pat.sub(replace, text)
    if not seen and not uninstall:
        new = (text.rstrip("\n") + "\n\n" if text.strip() else "") + block
    w.write(path, new, "codex MCP")


def claude_desktop_mcp(w, uninstall=False):
    """The desktop app rewrites the file from memory: a change made while it runs is lost."""
    before = w.changes
    json_mcp(P.claude_desktop_config(), "claude desktop MCP (Chat/Cowork)", w, uninstall)
    if w.changes > before and P.app_running("Claude"):
        print("[!!]  The Claude desktop app is running: quit it completely (tray icon > Quit) and reopen it, "
              "or it overwrites this change")


def _router_commands(node):
    """Every hook "command" string anywhere in a parsed config that is one of ours (current or pre-rename)."""
    if isinstance(node, dict):
        for key, value in node.items():
            if key == "command" and isinstance(value, str) and is_router_cmd(value):
                yield value
            else:
                yield from _router_commands(value)
    elif isinstance(node, list):
        for item in node:
            yield from _router_commands(item)


def _json_entries(hooks_path, mcp_path):
    """(has router entries, has pre-rename entries) in one tool's hooks file and JSON MCP config."""
    found = legacy_found = False
    try:
        cmds = list(_router_commands(load(hooks_path))) if hooks_path else []
        servers = load(mcp_path).get("mcpServers") or {} if mcp_path else {}
    except BadConfig:
        return False, False
    found = bool(cmds) or MCP_NAME in servers or legacy.MCP_NAME in servers
    legacy_found = any(is_legacy_cmd(c) for c in cmds) or legacy.MCP_NAME in servers
    return found, legacy_found


def _codex_entries():
    path = P.PATHS["codex_config"]
    text = path.read_text(encoding="utf-8") if path.exists() else ""
    old, new = f"[mcp_servers.{legacy.MCP_NAME}]" in text, f"[mcp_servers.{MCP_NAME}]" in text
    found, legacy_found = _json_entries(P.PATHS["codex_hooks"], None)
    return found or old or new, legacy_found or old


def configured_providers():
    """([providers whose configs already hold a router hook or MCP entry], any entry from before the rename).
    Used to re-point an existing install; a tool that was never set up is not added."""
    checks = {"claude": _json_entries(P.PATHS["claude_settings"], P.claude_desktop_config()),
              "codex": _codex_entries(),
              "antigravity": _json_entries(P.PATHS["agy_hooks"], P.PATHS["agy_mcp"])}
    return [p for p in ALL if checks[p][0]], any(c[1] for c in checks.values())


def install_shims(w):
    w.write(SHIM_HOOK, shim("trirouter.hooks"), "hook shim")
    w.write(SHIM_MCP, shim("trirouter.mcp_server"), "MCP shim")
    w.write(SHIM_ROUTE, shim("trirouter", "route"), "route shim")


def install(providers=ALL, apply=False, uninstall=False, launcher=True):
    """Number of files that changed (or would change)."""
    w = Writer(apply)
    if not uninstall:
        install_shims(w)
    if launcher:
        (uninstall_launcher if uninstall else install_launcher)(w)
    steps = []
    if "claude" in providers:
        steps += [lambda: claude_codex_hooks(P.PATHS["claude_settings"], "claude", w, uninstall),
                  lambda: claude_desktop_mcp(w, uninstall)]
    if "codex" in providers:
        steps += [lambda: claude_codex_hooks(P.PATHS["codex_hooks"], "codex", w, uninstall),
                  lambda: codex_mcp(P.PATHS["codex_config"], w, uninstall)]
    if "antigravity" in providers:
        steps += [lambda: antigravity_hooks(P.PATHS["agy_hooks"], w, uninstall),
                  lambda: json_mcp(P.PATHS["agy_mcp"], "antigravity MCP", w, uninstall)]
    for step in steps:
        try:
            step()
        except BadConfig as exc:  # one broken file must not stop the others
            print(f"[FAIL] {exc}")
    return w.changes



# ---- the `trirouter` command -------------------------------------------------------------------------

LAUNCHER_LABEL = "trirouter command"
LAUNCHER_PY_TEMPLATE = '''# generated by trirouter's installer - runs `python -m trirouter` from the repository
import os, runpy, sys
sys.path.insert(0, r"{repo}")
os.environ["TRIROUTER_PROG"] = "trirouter"
runpy.run_module("trirouter", run_name="__main__", alter_sys=True)
'''
PROFILE_LINE = 'export PATH="$HOME/.local/bin:$PATH"'


def launcher_py_path():
    return BIN / "trirouter.py" if P.IS_WINDOWS else BIN / "trirouter"


def launcher_cmd_path():
    return BIN / "trirouter.cmd"


def launcher_py(python=None, windows=None, repo=None):
    """Source of the Python launcher. On POSIX it is the executable itself (shebang to the interpreter);
    on Windows trirouter.cmd runs it."""
    windows = P.IS_WINDOWS if windows is None else windows
    body = LAUNCHER_PY_TEMPLATE.format(repo=repo or REPO)
    if windows:
        return body
    exe = python or P.python_exe()
    if any(c.isspace() for c in str(exe)):  # a shebang cannot hold a space: re-exec through sh
        return '#!/bin/sh\n\'\'\'\'exec "' + str(exe) + '" "$0" "$@" # \'\'\'\n' + body
    return f"#!{exe}\n" + body


def launcher_cmd(python=None):
    """trirouter.cmd: the same interpreter as the hooks, python.exe (never pythonw.exe), all arguments passed on."""
    exe = str(python or P.python_exe())
    return f'@echo off\r\nrem generated by the trirouter installer\r\n"{exe}" "%~dp0trirouter.py" %*\r\n'


# --- the Windows user PATH (HKCU\Environment); never the system PATH. Injectable for tests. ---

def _env_key(access):
    import winreg
    return winreg.OpenKey(winreg.HKEY_CURRENT_USER, "Environment", 0, access)


def user_path_read():
    """(value, registry type) of the user's Path; ("", REG_EXPAND_SZ) when there is none."""
    import winreg
    with _env_key(winreg.KEY_READ) as key:
        try:
            return winreg.QueryValueEx(key, "Path")
        except FileNotFoundError:
            return "", winreg.REG_EXPAND_SZ


def user_path_write(value, kind):
    import winreg
    with _env_key(winreg.KEY_SET_VALUE) as key:
        winreg.SetValueEx(key, "Path", 0, kind, value)


def broadcast_env_change():
    """WM_SETTINGCHANGE, so newly started programs re-read the environment."""
    import ctypes
    result = ctypes.c_ulong()
    ctypes.windll.user32.SendMessageTimeoutW(0xFFFF, 0x001A, 0, "Environment", 0x0002, 5000, ctypes.byref(result))


def _norm_entry(entry):
    entry = entry.strip().strip('"')
    # ntpath explicitly: this is Windows registry logic, and it must compare the same way on every OS
    return ntpath.normcase(ntpath.normpath(ntpath.expandvars(entry))) if entry else ""


def path_has(value, entry):
    return _norm_entry(str(entry)) in {_norm_entry(e) for e in value.split(";")}


def path_with(value, entry):
    """`value` with `entry` appended, unless it is there already (no duplicates)."""
    return value if path_has(value, entry) else (value.rstrip(";") + ";" if value else "") + str(entry)


def path_without(value, entry):
    target = _norm_entry(str(entry))
    return ";".join(e for e in value.split(";") if e and _norm_entry(e) != target)


def posix_path_has(directory, path=None):
    path = os.environ.get("PATH", "") if path is None else path
    return str(directory) in [e.rstrip("/") for e in path.split(os.pathsep)]


def legacy_launcher_py_path():
    return LEGACY_BIN / "trirouter.py" if P.IS_WINDOWS else LEGACY_BIN / "trirouter"


def _posix_link_state():
    """"ok" (our link), "legacy" (our link from before the rename: points into ~/.jev-router/bin, re-pointed),
    "missing", or "foreign" (something else is in the way: never overwritten)."""
    link = LOCAL_BIN / "trirouter"
    if link.is_symlink():
        target = os.path.realpath(link)
        if target == os.path.realpath(launcher_py_path()):
            return "ok"
        return "legacy" if target == os.path.realpath(legacy_launcher_py_path()) else "foreign"
    return "foreign" if link.exists() else "missing"


def _file_matches(path, content):
    try:
        return Path(path).read_bytes().decode("utf-8").replace("\r\n", "\n") == content.replace("\r\n", "\n")
    except (OSError, ValueError):
        return False


def _write_launcher(path, content):
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="") as f:  # keep the line endings exactly
        f.write(content)
    if not P.IS_WINDOWS:
        os.chmod(path, 0o755)


def _make_posix_link():
    LOCAL_BIN.mkdir(parents=True, exist_ok=True)
    link = LOCAL_BIN / "trirouter"
    if link.is_symlink():  # our pre-rename link: re-point
        link.unlink()
    os.symlink(launcher_py_path(), link)


def _set_user_path(value, kind):
    user_path_write(value, kind)
    broadcast_env_change()


def _remove_from_user_path(value, kind):
    _set_user_path(path_without(path_without(value, BIN), LEGACY_BIN), kind)


def launcher_plan():
    """[(message, action)] still to do for the `trirouter` command; an empty list means up to date."""
    plan = []
    files = [(launcher_py_path(), launcher_py())]
    if P.IS_WINDOWS:
        files.append((launcher_cmd_path(), launcher_cmd()))
    for path, content in files:
        if not _file_matches(path, content) or (not P.IS_WINDOWS and not os.access(path, os.X_OK)):
            plan.append((f"{'update' if Path(path).exists() else 'create'} {path}",
                         lambda path=path, content=content: _write_launcher(path, content)))
    if P.IS_WINDOWS:
        value, kind = user_path_read()
        msgs = ([f"remove the old {LEGACY_BIN} from your user PATH"] if path_has(value, LEGACY_BIN) else []) + (
            [f"add {BIN} to your user PATH"] if not path_has(value, BIN) else [])
        if msgs:  # one registry write: the legacy entry out, the new one in (never twice, no duplicates)
            wanted = path_with(path_without(value, LEGACY_BIN), BIN)
            plan.append(("; ".join(msgs), lambda: _set_user_path(wanted, kind)))
    else:
        state = _posix_link_state()
        if state in ("missing", "legacy"):
            plan.append((f"{'re-point' if state == 'legacy' else 'link'} {LOCAL_BIN / 'trirouter'} -> {launcher_py_path()}",
                         _make_posix_link))
    return plan


def _run_plan(w, plan):
    for message, action in plan:
        w.changes += 1
        print(("[DO]  " if w.apply else "[DRY] ") + f"{LAUNCHER_LABEL}: {message}")
        if w.apply:
            try:
                action()
            except OSError as exc:
                print(f"[FAIL] {LAUNCHER_LABEL}: {exc}")


def install_launcher(w):
    """Writes the `trirouter` launcher and puts it on PATH (user PATH on Windows; on POSIX only a link in
    ~/.local/bin: shell profiles are never edited, the line to add is printed)."""
    plan = launcher_plan()
    if not plan:
        print(f"[OK]  {LAUNCHER_LABEL}: up to date")
    _run_plan(w, plan)
    if P.IS_WINDOWS:
        if plan and w.apply:
            print("[!!]  Terminals that are already open keep the old PATH: close and reopen them, "
                  "then run `trirouter help`.")
    elif _posix_link_state() == "foreign":
        print(f"[!!]  {LOCAL_BIN / 'trirouter'} exists and is not this launcher: left alone. "
              f"Run it directly: {launcher_py_path()}")
    elif not posix_path_has(LOCAL_BIN):
        print(f"[!!]  {LOCAL_BIN} is not on your PATH. Add this line to your shell profile "
              f"(~/.bashrc, ~/.zshrc, ...), then open a new terminal:\n          {PROFILE_LINE}")


def uninstall_launcher(w):
    """Removes the launcher, the ~/.local/bin link (only ours) and the PATH entry."""
    todo = []
    for base in (BIN, LEGACY_BIN):  # the pre-rename folder too
        for name in ("trirouter.py", "trirouter.cmd") if P.IS_WINDOWS else ("trirouter",):
            path = base / name
            if path.exists():
                todo.append((f"remove {path}", lambda path=path: Path(path).unlink()))
    if not P.IS_WINDOWS and _posix_link_state() in ("ok", "legacy"):
        todo.append((f"remove {LOCAL_BIN / 'trirouter'}", lambda: (LOCAL_BIN / "trirouter").unlink()))
    if P.IS_WINDOWS:
        value, kind = user_path_read()
        found = [base for base in (BIN, LEGACY_BIN) if path_has(value, base)]
        if found:
            todo.append((f"remove {' and '.join(str(b) for b in found)} from your user PATH",
                         lambda: _remove_from_user_path(value, kind)))
    if not todo:
        print(f"[OK]  {LAUNCHER_LABEL}: not installed")
    _run_plan(w, todo)


def launcher_status():
    """(ok, detail) for `doctor`: the launcher exists and its folder is on PATH."""
    present = launcher_py_path().is_file() and (not P.IS_WINDOWS or launcher_cmd_path().is_file())
    if not present:
        return False, f"missing - run: {P.command_hint('setup --yes')}"
    try:
        on_path = path_has(user_path_read()[0], BIN) if P.IS_WINDOWS else (
            _posix_link_state() == "ok" and posix_path_has(LOCAL_BIN))
    except OSError:
        on_path = False
    where = launcher_cmd_path() if P.IS_WINDOWS else launcher_py_path()
    if not on_path:
        return False, f"{where} is installed, but not on PATH - run: {P.command_hint('setup --yes')}"
    return True, f"{where} (on PATH)"
