"""Shell tab completion (trirouter/completion.py): the scripts cover every command, subcommand, flag and flag value
of the manual; the shell and profile choice per OS (simulated); install is idempotent, keeps a .bak and the line
endings, honours --dry-run and can be removed; setup installs it unless --no-completion. Where bash or PowerShell
is installed the generated script is also checked by the real shell."""
import os
import re
import shutil
import subprocess
from pathlib import Path, PureWindowsPath

import pytest

from trirouter import cli, completion as C, manual, platforms as P


def all_long_flags():
    return {f.long for c in manual.COMMANDS.values() for f in manual.all_flags(c)}


@pytest.mark.parametrize("shell", C.SHELLS)
def test_every_command_subcommand_flag_and_value_is_in_the_script(shell):
    text = C.script(shell)
    for c in manual.ORDER:
        assert c in text
    for subs in manual.SUBCOMMANDS.values():
        for s in subs:
            assert s in text
    for flag in all_long_flags():
        assert (flag if shell != "fish" else f"-l {flag[2:]}") in text, flag
    for value in ("claude-chat", "on", "off"):
        assert value in text
    assert "generated by `trirouter setup`" in text
    body = chr(10).join(x for x in text.splitlines() if not x.lstrip().startswith("#"))  # without comments
    for doc in (d for _, _, d in manual.TOP_FLAGS):
        body = body.replace(doc.rstrip("."), "")
    for gone in ("--probe", "--shell", "--install"):
        assert gone not in body, gone
    for line in (x for x in body.splitlines() if "uninstall" in x):  # the places that list the commands
        for gone in ("detect", "completion", "version"):
            assert not re.search(rf"(?<![\w-]){gone}(?![\w-])", line), (gone, line)
    for flag in ("--version", "-V"):
        assert (flag if shell != "fish" else {"--version": "-l version", "-V": "-s V"}[flag]) in text, flag


def test_value_flags_end_in_equals_and_values_follow_the_hint():
    assert C.flags_of("models") == ["--discover", "--auto=", "--dry-run", "--help"]
    auto = next(f for f in manual.COMMANDS["models"].flags if f.long == "--auto")
    assert C.values_of(auto) == ["on", "off"]
    provider = next(f for f in manual.COMMANDS["route"].flags if f.long == "--provider")
    assert C.values_of(provider) == ["claude", "codex", "antigravity", "claude-chat"]


# ---- shell and profile per OS (simulated) -----------------------------------------------------------------------

@pytest.fixture
def os_sim(monkeypatch, tmp_path):
    def set_os(name, pwsh=False):
        monkeypatch.setattr(P, "IS_WINDOWS", name == "windows")
        monkeypatch.setattr(P, "IS_MAC", name == "mac")
        monkeypatch.setattr(P, "HOME", tmp_path / "home")
        monkeypatch.setattr(P, "find_exe", lambda exe: f"/usr/bin/{exe}" if pwsh and exe == "pwsh" else None)
        for var in ("SHELL", "ZDOTDIR", "XDG_CONFIG_HOME"):
            monkeypatch.delenv(var, raising=False)
    return set_os


@pytest.mark.parametrize("osname, shell_env, pwsh, expected", [
    ("windows", None, False, ["powershell"]),
    ("windows", "/usr/bin/bash", False, ["bash", "powershell"]),        # Git Bash
    ("mac", None, False, ["zsh"]),                                      # macOS default shell
    ("mac", "/bin/bash", True, ["bash", "powershell"]),
    ("linux", None, False, ["bash"]),
    ("linux", "/usr/bin/fish", False, ["fish"]),
    ("linux", "/bin/zsh", True, ["zsh", "powershell"]),
])
def test_setup_picks_the_shells_per_os(os_sim, osname, shell_env, pwsh, expected):
    os_sim(osname, pwsh)
    env = {"SHELL": shell_env} if shell_env else {}
    assert C.setup_shells(env) == expected
    assert C.detect_shell(env) == expected[0]


def test_profiles_per_os(os_sim, monkeypatch, tmp_path):
    home = tmp_path / "home"
    os_sim("mac")
    assert C.profiles("bash") == [home / ".bash_profile"]   # macOS login shells skip ~/.bashrc
    assert C.profiles("zsh") == [home / ".zshrc"]
    os_sim("linux")
    assert C.profiles("bash") == [home / ".bashrc"]
    monkeypatch.setenv("ZDOTDIR", str(tmp_path / "zdot"))
    assert C.profiles("zsh") == [tmp_path / "zdot" / ".zshrc"]
    assert C.profiles("fish") == [] and C.profile_block("fish") is None
    assert C.script_path("fish") == home / ".config" / "fish" / "completions" / "trirouter.fish"
    monkeypatch.setenv("XDG_CONFIG_HOME", str(tmp_path / "xdg"))
    assert C.script_path("fish") == tmp_path / "xdg" / "fish" / "completions" / "trirouter.fish"
    os_sim("windows")
    assert C.profiles("bash") == [home / ".bashrc"]  # Git Bash: its ~/.bash_profile sources ~/.bashrc


def test_powershell_profiles_are_asked_from_each_edition(os_sim, monkeypatch, tmp_path):
    os_sim("windows")
    monkeypatch.setattr(P, "find_exe", lambda exe: exe if exe in ("pwsh", "powershell") else None)
    answers = {"pwsh": (0, r"C:\Users\u\OneDrive\Documents\PowerShell\Microsoft.PowerShell_profile.ps1"),
               "powershell": (0, r"C:\Users\u\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1")}
    monkeypatch.setattr(P, "run", lambda argv, timeout=30, env=None: answers[argv[0]])
    assert [PureWindowsPath(str(p)).parent.name for p in C.powershell_profiles()] == ["PowerShell", "WindowsPowerShell"]
    os_sim("linux", pwsh=True)  # no Windows PowerShell; pwsh failed to answer: its documented default
    monkeypatch.setattr(P, "run", lambda argv, timeout=30, env=None: (1, "boom"))
    assert C.powershell_profiles() == [tmp_path / "home" / ".config" / "powershell" / "Microsoft.PowerShell_profile.ps1"]


# ---- install ----------------------------------------------------------------------------------------------------

@pytest.fixture
def home(os_sim, monkeypatch, tmp_path):
    os_sim("linux")
    ps_profile = tmp_path / "Documents" / "PowerShell" / "Microsoft.PowerShell_profile.ps1"
    monkeypatch.setattr(C, "powershell_profiles", lambda: [ps_profile])
    h = tmp_path / "home"
    h.mkdir()
    return h, ps_profile


def quiet(_msg):
    pass


def test_install_is_idempotent_keeps_content_and_a_bak(home):
    h, ps_profile = home
    (h / ".bashrc").write_bytes(b"export A=1\n")
    shells = ["bash", "zsh", "fish", "powershell"]
    assert C.install(shells, apply=True, say=quiet) == 7  # 4 scripts, 3 profiles (fish has none)
    bashrc = (h / ".bashrc").read_text(encoding="utf-8")
    assert bashrc.startswith("export A=1\n") and bashrc.count(C.BEGIN) == 1 and ".trirouter/completion/trirouter.bash" in bashrc
    assert (h / ".bashrc.bak").read_bytes() == b"export A=1\n"
    assert not (h / ".zshrc.bak").exists()  # nothing to keep: it did not exist
    assert ps_profile.read_text(encoding="utf-8").count(C.BEGIN) == 1
    assert (h / ".trirouter" / "completion" / "trirouter.ps1").is_file()
    assert (h / ".config" / "fish" / "completions" / "trirouter.fish").is_file()
    assert C.install(shells, apply=True, say=quiet) == 0  # second run: nothing to do
    assert (h / ".bashrc").read_text(encoding="utf-8") == bashrc
    assert sorted(C.installed()) == sorted(shells)


def test_install_replaces_an_old_block_in_place_and_keeps_crlf(home):
    h, _ = home
    (h / ".bashrc").write_bytes(b"A=1\r\n" + C.BEGIN.encode() + b"\r\nold line\r\n" + C.END.encode() + b"\r\nB=2\r\n")
    C.install(["bash"], apply=True, say=quiet)
    raw = (h / ".bashrc").read_bytes()
    assert b"old line" not in raw and raw.count(C.BEGIN.encode()) == 1
    assert raw.startswith(b"A=1\r\n") and raw.endswith(b"B=2\r\n") and b"\n" not in raw.replace(b"\r\n", b"")


def test_dry_run_changes_nothing(home):
    h, ps_profile = home
    messages = []
    assert C.install(["bash", "powershell"], apply=False, say=messages.append) == 4
    assert not (h / ".bashrc").exists() and not ps_profile.exists() and not (h / ".trirouter").exists()
    assert all(m.startswith("[DRY]") for m in messages)


def test_remove_takes_out_the_blocks_and_scripts(home):
    h, ps_profile = home
    (h / ".bashrc").write_text("export A=1\n", encoding="utf-8")
    C.install(["bash", "fish", "powershell"], apply=True, say=quiet)
    assert C.remove(apply=True, say=quiet) >= 4
    assert (h / ".bashrc").read_text(encoding="utf-8").strip() == "export A=1"
    assert C.BEGIN not in ps_profile.read_text(encoding="utf-8")
    assert not C.installed() and C.remove(apply=True, say=quiet) == 0


def test_a_profile_that_is_not_utf8_is_left_alone(home):
    h, _ = home
    (h / ".bashrc").write_bytes(b"\xff\xfe\x00b\x00a")
    messages = []
    C.install(["bash"], apply=True, say=messages.append)
    assert (h / ".bashrc").read_bytes() == b"\xff\xfe\x00b\x00a" and any("left alone" in m for m in messages)


def test_with_block_appends_and_replaces():
    block = C.profile_block("bash")
    assert C.with_block("", block) == block
    once = C.with_block("x=1", block)
    assert once == "x=1\n\n" + block and C.with_block(once, block) == once
    assert C.with_block(once, None).strip() == "x=1"


# ---- CLI and setup ----------------------------------------------------------------------------------------------

def test_completion_is_no_command_any_more(capsys, monkeypatch):
    monkeypatch.setenv("TRIROUTER_PROG", "trirouter")
    with pytest.raises(SystemExit) as exc:
        cli.main(["completion", "--shell=fish"])
    err = capsys.readouterr().err
    assert exc.value.code == 2 and "completion was removed" in err and "trirouter setup" in err and "trirouter uninstall" in err


def test_scripts_offer_exactly_the_nine_commands(monkeypatch):
    assert C.commands() == ["setup", "models", "skills", "quarantine", "remote", "doctor", "route", "uninstall", "help"]
    assert "--version -V --help -h" in C.bash_script()


def test_setup_installs_completion_unless_told_not_to(home, monkeypatch, capsys):
    h, _ = home
    monkeypatch.setattr(cli, "DRY", False)
    monkeypatch.setattr(cli, "FLAGS", {})
    monkeypatch.setenv("SHELL", "/bin/bash")
    cli.setup_completion()
    assert C.BEGIN in (h / ".bashrc").read_text(encoding="utf-8")
    C.remove(apply=True, say=quiet)
    monkeypatch.setattr(cli, "FLAGS", {"--no-completion": True})
    cli.setup_completion()
    assert C.BEGIN not in (h / ".bashrc").read_text(encoding="utf-8") and "skipped" in capsys.readouterr().out


# ---- the real shells, where installed ---------------------------------------------------------------------------

def real_bash():
    path = shutil.which("bash")
    if not path or (P.IS_WINDOWS and ("system32" in path.lower() or "windowsapps" in path.lower())):
        return None  # the WSL launcher, not a bash for this machine
    return path


@pytest.mark.skipif(not real_bash(), reason="bash not installed")
def test_bash_script_completes_commands_flags_and_values(tmp_path):
    script = tmp_path / "t.bash"
    script.write_bytes(C.bash_script().encode())
    probe = tmp_path / "probe.sh"
    probe.write_bytes(b'''. "$1"
complete -p trirouter
t() { COMP_WORDS=("$@"); COMP_CWORD=$(( ${#COMP_WORDS[@]} - 1 )); COMPREPLY=(); _trirouter_completion; echo "${COMPREPLY[*]}"; }
t trirouter mo
t trirouter models --
t trirouter models --auto = ""
t trirouter quarantine ""
t trirouter help quarantine ""
t trirouter ""
t trirouter -
t trirouter --v
''')
    out = subprocess.run([real_bash(), str(probe), str(script)], capture_output=True, text=True, timeout=60)
    assert out.returncode == 0, out.stderr
    lines = out.stdout.splitlines()
    assert lines[0] == "complete -o default -F _trirouter_completion trirouter"
    assert lines[1] == "models"
    assert lines[2] == "--discover --auto= --dry-run --help"
    assert lines[3] == "on off" and lines[4] == lines[5] == "list restore purge"
    assert lines[6] == "setup models skills quarantine remote doctor route uninstall help"
    assert lines[7] == "--version -V --help -h" and lines[8] == "--version"


def real_powershell():
    for exe in ("pwsh", "powershell"):
        path = shutil.which(exe)
        if path:
            return path
    return None


@pytest.mark.skipif(not real_powershell(), reason="PowerShell not installed")
def test_powershell_script_parses_and_completes(tmp_path):
    script = tmp_path / "t.ps1"
    script.write_text(C.powershell_script(), encoding="utf-8")
    test = tmp_path / "test.ps1"
    test.write_text('''param($s)
. $s
foreach ($line in @('trirouter mo', 'trirouter models --', 'trirouter models --auto=', 'trirouter quarantine ', 'trirouter -')) {
  $r = TabExpansion2 -inputScript $line -cursorColumn $line.Length
  ($r.CompletionMatches | ForEach-Object CompletionText) -join ' '
}
''', encoding="utf-8")
    out = subprocess.run([real_powershell(), "-NoProfile", "-ExecutionPolicy", "Bypass", "-File", str(test), str(script)],
                         capture_output=True, text=True, timeout=120)
    assert out.returncode == 0 and not out.stderr.strip(), out.stderr
    assert out.stdout.splitlines() == ["models", "--discover --auto= --dry-run --help", "--auto=on --auto=off",
                                       "list restore purge", "--version -V --help -h"]


# ---- the PowerShell `trirouter` function (no trirouter.cmd, so no "Terminate batch job" after Ctrl+C) ------------

def test_powershell_block_defines_a_trirouter_function_that_bypasses_the_cmd_launcher(monkeypatch):
    monkeypatch.setattr(P, "IS_WINDOWS", True)
    monkeypatch.setattr(P, "python_exe", lambda: r"C:\Program Files\Py'thon\python.exe")
    block = C.profile_block("powershell")
    assert block.startswith(C.BEGIN) and block.endswith(C.END + "\n")
    assert ("function global:trirouter { & 'C:\Program Files\Py''thon\python.exe' "
            '"$HOME/.trirouter/bin/trirouter.py" @args }') in block
    assert ".cmd" not in block and "exit" not in block  # $LASTEXITCODE is left as the program set it
    assert C.with_block(C.with_block("", block), block) == block  # idempotent


def test_posix_powershell_function_runs_the_launcher_and_other_shells_get_none(monkeypatch):
    monkeypatch.setattr(P, "IS_WINDOWS", False)
    assert '& "$HOME/.trirouter/bin/trirouter" @args' in C.profile_block("powershell")
    assert "function" not in C.profile_block("bash")


def test_removing_the_block_removes_the_function(monkeypatch):
    block = C.profile_block("powershell")
    text = C.with_block("Set-Alias a b\n", block)
    assert "function global:trirouter" in text
    assert "trirouter" not in C.with_block(text, None)
