#!/usr/bin/env python3
"""Installs or removes the router's hooks and MCP server for Claude Code, Codex and Antigravity.

Every entry calls a shim in ~/.jev-router/bin/, so moving the repository only requires re-running
the installer. A changed file's original is kept once as `<file>.bak`; a config file that is not
valid JSON is reported and left untouched.

    claude       UserPromptSubmit, Stop, StopFailure, SessionEnd, SubagentStart    ~/.claude/settings.json
    codex        UserPromptSubmit + Stop    ~/.codex/hooks.json (trust once via /hooks)
    antigravity  PreInvocation + Stop       ~/.gemini/config/hooks.json

It also installs the `trirouter` command: a launcher in ~/.jev-router/bin (Windows: trirouter.cmd, with
that folder added to the USER PATH; macOS / Linux: an executable plus a link in ~/.local/bin).
"""
import json
import os
import re
import sys
from pathlib import Path

from . import platforms as P

REPO = Path(__file__).resolve().parent.parent
BIN = P.HOME / ".jev-router" / "bin"
SHIM_HOOK, SHIM_MCP, SHIM_ROUTE = BIN / "run_hook.py", BIN / "mcp_server.py", BIN / "route.py"
LOCAL_BIN = P.HOME / ".local" / "bin"  # macOS / Linux: where the `trirouter` link goes
ALL = ("claude", "codex", "antigravity")
SHIM_TEMPLATE = '''# generated by jev-router's installer - runs {target} from the repository
import runpy, sys
sys.path.insert(0, r"{repo}")
{argv}runpy.run_module("{module}", run_name="__main__", alter_sys=True)
'''


def shim(module, command=None):
    """Shim source that runs `module` from this repository; `command` becomes its first argument."""
    argv = f'sys.argv[1:1] = ["{command}"]\n' if command else ""
    target = f"{module} {command}" if command else module
    return SHIM_TEMPLATE.format(target=target, repo=REPO, module=module, argv=argv)


class Writer:
    def __init__(self, apply):
        self.apply = apply
        self.changes = 0

    def write(self, path, content, label):
        path = Path(path)
        old = path.read_text(encoding="utf-8") if path.exists() else None
        if old == content:
            print(f"[OK]  {label}: up to date")
            return
        self.changes += 1
        print(("[DO]  " if self.apply else "[DRY] ") + f"{label}: {'update' if old is not None else 'create'} {path}")
        if self.apply:
            path.parent.mkdir(parents=True, exist_ok=True)
            bak = path.with_name(path.name + ".bak")
            if old is not None and not bak.exists():  # keep the original, pre-jev-router version
                bak.write_text(old, encoding="utf-8")
            path.write_text(content, encoding="utf-8")


def fwd(p):
    return str(p).replace("\\", "/")


class BadConfig(Exception):
    pass


def load(path):
    path = Path(path)
    if not path.exists() or not path.read_text(encoding="utf-8").strip():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8-sig"))
    except ValueError as exc:
        raise BadConfig(f"{path} is not valid JSON ({exc}) - fix it, then re-run") from exc
    if not isinstance(data, dict):
        raise BadConfig(f"{path} does not contain a JSON object - fix it, then re-run")
    return data


def is_router_cmd(cmd):
    c = (cmd or "").replace("\\", "/").lower()
    return ("router/run_hook.py" in c or "jev_router.hooks" in c or ".jev-router/bin/run_hook.py" in c
            or fwd(SHIM_HOOK).lower() in c or fwd(P.short_path(SHIM_HOOK)).lower() in c)


def hook_cmd(provider, event):
    return f"{P.python_cmd()} {P.shell_arg(SHIM_HOOK)} {provider} {event}"


def _strip_router(groups):
    kept = []
    for g in groups or []:
        hs = [h for h in g.get("hooks", []) if not is_router_cmd(h.get("command"))]
        if hs:
            kept.append({**g, "hooks": hs})
    return kept


HOOK_EVENTS = {
    # StopFailure / SessionEnd release the queue when a turn dies on an API error or the session ends;
    # SubagentStart records which worker the model really delegated to.
    # SessionStart purges expired quarantine entries (at most every 6 hours; prints nothing)
    "claude": ("UserPromptSubmit", "Stop", "StopFailure", "SessionEnd", "SubagentStart", "SessionStart"),
    "codex": ("UserPromptSubmit", "Stop"),
}
ROUTER_EVENTS = tuple(dict.fromkeys(e for events in HOOK_EVENTS.values() for e in events))


def claude_codex_hooks(path, provider, w, uninstall=False):
    cfg = load(path)
    hooks = cfg.setdefault("hooks", {})
    wanted = () if uninstall else HOOK_EVENTS[provider]
    for event in ROUTER_EVENTS:
        if event not in hooks and event not in wanted:
            continue
        groups = _strip_router(hooks.get(event))
        matcher = provider == "codex" and event == "UserPromptSubmit"
        if event in wanted:
            entry = {"hooks": [{"type": "command", "command": hook_cmd(provider, event), "timeout": 10}]}
            groups.append({"matcher": "*", **entry} if matcher else entry)
        if groups:
            hooks[event] = groups
        else:
            hooks.pop(event, None)
    if not hooks:
        cfg.pop("hooks", None)
    w.write(path, json.dumps(cfg, indent=2, ensure_ascii=False) + "\n", f"{provider} hooks")


AGY_EVENTS = ("PreToolUse", "PostToolUse", "PreInvocation", "PostInvocation", "Stop")


def _strip_router_events(spec):
    for event in ("PreInvocation", "Stop"):
        if event in spec:
            spec[event] = [h for h in spec[event] if not is_router_cmd(h.get("command"))]
            if not spec[event]:
                del spec[event]


def antigravity_hooks(path, w, uninstall=False):
    cfg = load(path)
    for spec in cfg.values():
        if isinstance(spec, dict):
            _strip_router_events(spec)
    cfg = {name: spec for name, spec in cfg.items()
           if not isinstance(spec, dict) or any(k in spec for k in AGY_EVENTS)}
    if not uninstall:
        cfg["router"] = {e: [{"type": "command", "command": hook_cmd("antigravity", e), "timeout": 10}]
                         for e in ("PreInvocation", "Stop")}
    w.write(path, json.dumps(cfg, indent=2, ensure_ascii=False) + "\n", "antigravity hooks")


def json_mcp(path, label, w, uninstall=False):
    cfg = load(path)
    servers = cfg.setdefault("mcpServers", {})
    if uninstall:
        servers.pop("jev-router", None)
    else:
        # MCP clients exec "command" directly, without a shell: never shell-quoted
        servers["jev-router"] = {"command": fwd(P.python_exe_windowless()), "args": [fwd(SHIM_MCP)]}
    w.write(path, json.dumps(cfg, indent=2, ensure_ascii=False) + "\n", label)


def codex_mcp(path, w, uninstall=False):
    text = Path(path).read_text(encoding="utf-8") if Path(path).exists() else ""
    # the section ends at the next table or comment line (our generated agents block starts with one)
    pat = re.compile(r"\[mcp_servers\.jev-router\]\n(?:\n|[^\[#\n].*(?:\n|\Z))*")
    block = f'[mcp_servers.jev-router]\ncommand = {json.dumps(fwd(P.python_exe_windowless()))}\nargs = [{json.dumps(fwd(SHIM_MCP))}]\n\n'
    m = pat.search(text)
    if uninstall:
        new = (text[:m.start()] + text[m.end():]) if m else text
    elif m:  # in place: other generated blocks may follow it
        new = text[:m.start()] + block + text[m.end():]
    else:
        new = (text.rstrip("\n") + "\n\n" if text.strip() else "") + block
    w.write(path, new, "codex MCP")


def claude_desktop_mcp(w, uninstall=False):
    """The desktop app rewrites the file from memory: a change made while it runs is lost."""
    before = w.changes
    json_mcp(P.claude_desktop_config(), "claude desktop MCP (Chat/Cowork)", w, uninstall)
    if w.changes > before and P.app_running("Claude"):
        print("[!!]  The Claude desktop app is running: quit it completely (tray icon > Quit) and reopen it, "
              "or it overwrites this change")


def install_shims(w):
    w.write(SHIM_HOOK, shim("jev_router.hooks"), "hook shim")
    w.write(SHIM_MCP, shim("jev_router.mcp_server"), "MCP shim")
    w.write(SHIM_ROUTE, shim("jev_router", "route"), "route shim")


def install(providers=ALL, apply=False, uninstall=False, launcher=True):
    """Number of files that changed (or would change)."""
    w = Writer(apply)
    if not uninstall:
        install_shims(w)
    if launcher:
        (uninstall_launcher if uninstall else install_launcher)(w)
    steps = []
    if "claude" in providers:
        steps += [lambda: claude_codex_hooks(P.PATHS["claude_settings"], "claude", w, uninstall),
                  lambda: claude_desktop_mcp(w, uninstall)]
    if "codex" in providers:
        steps += [lambda: claude_codex_hooks(P.PATHS["codex_hooks"], "codex", w, uninstall),
                  lambda: codex_mcp(P.PATHS["codex_config"], w, uninstall)]
    if "antigravity" in providers:
        steps += [lambda: antigravity_hooks(P.PATHS["agy_hooks"], w, uninstall),
                  lambda: json_mcp(P.PATHS["agy_mcp"], "antigravity MCP", w, uninstall)]
    for step in steps:
        try:
            step()
        except BadConfig as exc:  # one broken file must not stop the others
            print(f"[FAIL] {exc}")
    return w.changes



# ---- the `trirouter` command -------------------------------------------------------------------------

LAUNCHER_LABEL = "trirouter command"
LAUNCHER_PY_TEMPLATE = '''# generated by jev-router's installer - runs `python -m jev_router` from the repository
import os, runpy, sys
sys.path.insert(0, r"{repo}")
os.environ["TRIROUTER_PROG"] = "trirouter"
runpy.run_module("jev_router", run_name="__main__", alter_sys=True)
'''
PROFILE_LINE = 'export PATH="$HOME/.local/bin:$PATH"'


def launcher_py_path():
    return BIN / "trirouter.py" if P.IS_WINDOWS else BIN / "trirouter"


def launcher_cmd_path():
    return BIN / "trirouter.cmd"


def launcher_py(python=None, windows=None, repo=None):
    """Source of the Python launcher. On POSIX it is the executable itself (shebang to the interpreter);
    on Windows trirouter.cmd runs it."""
    windows = P.IS_WINDOWS if windows is None else windows
    body = LAUNCHER_PY_TEMPLATE.format(repo=repo or REPO)
    if windows:
        return body
    exe = python or P.python_exe()
    if any(c.isspace() for c in str(exe)):  # a shebang cannot hold a space: re-exec through sh
        return '#!/bin/sh\n\'\'\'\'exec "' + str(exe) + '" "$0" "$@" # \'\'\'\n' + body
    return f"#!{exe}\n" + body


def launcher_cmd(python=None):
    """trirouter.cmd: the same interpreter as the hooks, python.exe (never pythonw.exe), all arguments passed on."""
    exe = str(python or P.python_exe())
    return f'@echo off\r\nrem generated by the jev-router installer\r\n"{exe}" "%~dp0trirouter.py" %*\r\n'


# --- the Windows user PATH (HKCU\Environment); never the system PATH. Injectable for tests. ---

def _env_key(access):
    import winreg
    return winreg.OpenKey(winreg.HKEY_CURRENT_USER, "Environment", 0, access)


def user_path_read():
    """(value, registry type) of the user's Path; ("", REG_EXPAND_SZ) when there is none."""
    import winreg
    with _env_key(winreg.KEY_READ) as key:
        try:
            return winreg.QueryValueEx(key, "Path")
        except FileNotFoundError:
            return "", winreg.REG_EXPAND_SZ


def user_path_write(value, kind):
    import winreg
    with _env_key(winreg.KEY_SET_VALUE) as key:
        winreg.SetValueEx(key, "Path", 0, kind, value)


def broadcast_env_change():
    """WM_SETTINGCHANGE, so newly started programs re-read the environment."""
    import ctypes
    result = ctypes.c_ulong()
    ctypes.windll.user32.SendMessageTimeoutW(0xFFFF, 0x001A, 0, "Environment", 0x0002, 5000, ctypes.byref(result))


def _norm_entry(entry):
    entry = entry.strip().strip('"')
    return os.path.normcase(os.path.normpath(os.path.expandvars(entry))) if entry else ""


def path_has(value, entry):
    return _norm_entry(str(entry)) in {_norm_entry(e) for e in value.split(";")}


def path_with(value, entry):
    """`value` with `entry` appended, unless it is there already (no duplicates)."""
    return value if path_has(value, entry) else (value.rstrip(";") + ";" if value else "") + str(entry)


def path_without(value, entry):
    target = _norm_entry(str(entry))
    return ";".join(e for e in value.split(";") if e and _norm_entry(e) != target)


def posix_path_has(directory, path=None):
    path = os.environ.get("PATH", "") if path is None else path
    return str(directory) in [e.rstrip("/") for e in path.split(os.pathsep)]


def _posix_link_state():
    """"ok" (our link), "missing", or "foreign" (something else is in the way: never overwritten)."""
    link = LOCAL_BIN / "trirouter"
    if link.is_symlink():
        return "ok" if os.path.realpath(link) == os.path.realpath(launcher_py_path()) else "foreign"
    return "foreign" if link.exists() else "missing"


def _file_matches(path, content):
    try:
        return Path(path).read_bytes().decode("utf-8").replace("\r\n", "\n") == content.replace("\r\n", "\n")
    except (OSError, ValueError):
        return False


def _write_launcher(path, content):
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="") as f:  # keep the line endings exactly
        f.write(content)
    if not P.IS_WINDOWS:
        os.chmod(path, 0o755)


def _make_posix_link():
    LOCAL_BIN.mkdir(parents=True, exist_ok=True)
    os.symlink(launcher_py_path(), LOCAL_BIN / "trirouter")


def _add_to_user_path(value, kind):
    user_path_write(path_with(value, BIN), kind)
    broadcast_env_change()


def _remove_from_user_path(value, kind):
    user_path_write(path_without(value, BIN), kind)
    broadcast_env_change()


def launcher_plan():
    """[(message, action)] still to do for the `trirouter` command; an empty list means up to date."""
    plan = []
    files = [(launcher_py_path(), launcher_py())]
    if P.IS_WINDOWS:
        files.append((launcher_cmd_path(), launcher_cmd()))
    for path, content in files:
        if not _file_matches(path, content) or (not P.IS_WINDOWS and not os.access(path, os.X_OK)):
            plan.append((f"{'update' if Path(path).exists() else 'create'} {path}",
                         lambda path=path, content=content: _write_launcher(path, content)))
    if P.IS_WINDOWS:
        value, kind = user_path_read()
        if not path_has(value, BIN):
            plan.append((f"add {BIN} to your user PATH", lambda: _add_to_user_path(value, kind)))
    elif _posix_link_state() == "missing":
        plan.append((f"link {LOCAL_BIN / 'trirouter'} -> {launcher_py_path()}", _make_posix_link))
    return plan


def _run_plan(w, plan):
    for message, action in plan:
        w.changes += 1
        print(("[DO]  " if w.apply else "[DRY] ") + f"{LAUNCHER_LABEL}: {message}")
        if w.apply:
            try:
                action()
            except OSError as exc:
                print(f"[FAIL] {LAUNCHER_LABEL}: {exc}")


def install_launcher(w):
    """Writes the `trirouter` launcher and puts it on PATH (user PATH on Windows; on POSIX only a link in
    ~/.local/bin: shell profiles are never edited, the line to add is printed)."""
    plan = launcher_plan()
    if not plan:
        print(f"[OK]  {LAUNCHER_LABEL}: up to date")
    _run_plan(w, plan)
    if P.IS_WINDOWS:
        if plan and w.apply:
            print("[!!]  Terminals that are already open keep the old PATH: close and reopen them, "
                  "then run `trirouter help`.")
    elif _posix_link_state() == "foreign":
        print(f"[!!]  {LOCAL_BIN / 'trirouter'} exists and is not this launcher: left alone. "
              f"Run it directly: {launcher_py_path()}")
    elif not posix_path_has(LOCAL_BIN):
        print(f"[!!]  {LOCAL_BIN} is not on your PATH. Add this line to your shell profile "
              f"(~/.bashrc, ~/.zshrc, ...), then open a new terminal:\n          {PROFILE_LINE}")


def uninstall_launcher(w):
    """Removes the launcher, the ~/.local/bin link (only ours) and the PATH entry."""
    todo = []
    for path in (launcher_py_path(), launcher_cmd_path()) if P.IS_WINDOWS else (launcher_py_path(),):
        if Path(path).exists():
            todo.append((f"remove {path}", lambda path=path: Path(path).unlink()))
    if not P.IS_WINDOWS and _posix_link_state() == "ok":
        todo.append((f"remove {LOCAL_BIN / 'trirouter'}", lambda: (LOCAL_BIN / "trirouter").unlink()))
    if P.IS_WINDOWS:
        value, kind = user_path_read()
        if path_has(value, BIN):
            todo.append((f"remove {BIN} from your user PATH", lambda: _remove_from_user_path(value, kind)))
    if not todo:
        print(f"[OK]  {LAUNCHER_LABEL}: not installed")
    _run_plan(w, todo)


def launcher_status():
    """(ok, detail) for `doctor`: the launcher exists and its folder is on PATH."""
    present = launcher_py_path().is_file() and (not P.IS_WINDOWS or launcher_cmd_path().is_file())
    if not present:
        return False, f"missing - run: {P.command_hint('setup --yes')}"
    try:
        on_path = path_has(user_path_read()[0], BIN) if P.IS_WINDOWS else (
            _posix_link_state() == "ok" and posix_path_has(LOCAL_BIN))
    except OSError:
        on_path = False
    where = launcher_cmd_path() if P.IS_WINDOWS else launcher_py_path()
    if not on_path:
        return False, f"{where} is installed, but not on PATH - run: {P.command_hint('setup --yes')}"
    return True, f"{where} (on PATH)"
